export type Chat = {
  id?: string;
  name?: string;
  email?: string;
  phone?: string;
  bio?: string;
  lastMessage?: string;
  time?: string;
  unreadCount?: number;
  avatar?: string;
  isOnline?: boolean;
  lastSeen?: string;
  isGroup?: boolean;
  members?: string[];
  isLocked?: boolean;
};

export const chats: Chat[] = [
  {
    id: "1",
    name: "Aarav Sharma",
    email: "aarav.sharma@email.com",
    phone: "+91 98765 43210",
    bio: "Coffee ☕ | Travel ✈️ | Tech 💻",
    lastMessage: "Kal milte hain?",
    time: "09:45 AM",
    unreadCount: 2,
    avatar: "https://i.pravatar.cc/150?img=1",
    isOnline: true,
    lastSeen: "Active now",
    isGroup: false,
  },
  {
    id: "2",
    name: "Ananya Verma",
    email: "ananya.verma@email.com",
    phone: "+91 99887 66554",
    bio: "Bookworm 📚 | Music 🎶",
    lastMessage: "Maine files bhej di hain.",
    time: "08:30 AM",
    unreadCount: 0,
    avatar: "https://i.pravatar.cc/150?img=2",
    isOnline: false,
    lastSeen: "Last seen 30 minutes ago",
    isGroup: false,
    isLocked: true,
  },
  {
    id: "3",
    name: "Rohit Mehta",
    email: "rohit.mehta@email.com",
    phone: "+91 91234 56789",
    bio: "Fitness 💪 | Startup 🚀",
    lastMessage: "Weekend plan kare?",
    time: "Yesterday",
    unreadCount: 1,
    avatar: "https://i.pravatar.cc/150?img=3",
    isOnline: true,
    lastSeen: "Active now",
    isGroup: false,
  },
  {
    id: "4",
    name: "Sneha Iyer",
    email: "sneha.iyer@email.com",
    phone: "+91 90012 34567",
    bio: "Designer 🎨 | Minimalist",
    lastMessage: "Thanks 😊",
    time: "Yesterday",
    unreadCount: 0,
    avatar: "https://i.pravatar.cc/150?img=4",
    isOnline: false,
    lastSeen: "Last seen yesterday",
    isGroup: false,
    isLocked: true,
  },
  {
    id: "5",
    name: "Office Team",
    lastMessage: "Rahul: Latest build deploy ho gaya",
    time: "Mon",
    unreadCount: 5,
    avatar: "https://i.pravatar.cc/150?img=5",
    isGroup: true,
    members: ["Rahul", "Aarav", "Ananya", "Sneha", "Rohit"],
    bio: "Daily standup & updates",
  },
  {
    id: "6",
    name: "Rahul Khanna",
    email: "rahul.khanna@email.com",
    bio: "Product guy 📊",
    lastMessage: "Call karte hain?",
    time: "Mon",
    unreadCount: 0,
    avatar: "https://i.pravatar.cc/150?img=6",
    isOnline: true,
    lastSeen: "Active now",
    isGroup: false,
  },
  {
    id: "7",
    name: "Design Team",
    lastMessage: "Pooja: New mockups ready",
    time: "Sun",
    unreadCount: 3,
    avatar: "https://i.pravatar.cc/150?img=7",
    isGroup: true,
    members: ["Pooja", "Kunal", "Sneha"],
    bio: "UI/UX discussions",
  },
  {
    id: "8",
    name: "Kunal Patel",
    email: "kunal.patel@email.com",
    bio: "Gym • Work • Repeat 💪",
    lastMessage: "Done 👍",
    time: "Sun",
    unreadCount: 0,
    avatar: "https://i.pravatar.cc/150?img=8",
    isOnline: false,
    lastSeen: "Last seen 2 hours ago",
    isGroup: false,
  },
  {
    id: "9",
    name: "Family Group",
    lastMessage: "Maa: Dinner 8 baje 🍽️",
    time: "Sat",
    unreadCount: 6,
    avatar: "https://i.pravatar.cc/150?img=9",
    isGroup: true,
    members: ["Maa", "Papa", "Aarav", "Ananya"],
    bio: "Family updates",
  },
  {
    id: "10",
    name: "Pooja Singh",
    email: "pooja.singh@email.com",
    bio: "Nature 🌿 | Yoga 🧘‍♀️",
    lastMessage: "That’s amazing!",
    time: "Sat",
    unreadCount: 1,
    avatar: "https://i.pravatar.cc/150?img=10",
    isOnline: true,
    lastSeen: "Active now",
    isGroup: false,
  },
  {
    id: "11",
    name: "Marketing Team",
    lastMessage: "Campaign kal start hoga",
    time: "Fri",
    unreadCount: 2,
    avatar: "https://i.pravatar.cc/150?img=11",
    isGroup: true,
    members: ["Neha", "Amit", "Ravi"],
    bio: "Marketing plans & ideas",
  },
  {
    id: "12",
    name: "Amit Joshi",
    email: "amit.joshi@email.com",
    bio: "Startup | Growth 📈",
    lastMessage: "Kal baat karte hain",
    time: "Fri",
    unreadCount: 0,
    avatar: "https://i.pravatar.cc/150?img=12",
    isOnline: false,
    lastSeen: "Last seen Friday",
    isGroup: false,
  },
  {
    id: "13",
    name: "Gaming Friends",
    lastMessage: "Aaj raat match?",
    time: "Thu",
    unreadCount: 4,
    avatar: "https://i.pravatar.cc/150?img=13",
    isGroup: true,
    members: ["Ravi", "Karan", "Vikas"],
    bio: "Late night gaming 🎮",
  },
  {
    id: "14",
    name: "Ravi Malhotra",
    email: "ravi@email.com",
    bio: "Photography 📸",
    lastMessage: "Photo bhej raha hoon",
    time: "Thu",
    unreadCount: 1,
    avatar: "https://i.pravatar.cc/150?img=14",
    isOnline: true,
    lastSeen: "Active now",
    isGroup: false,
  },
  {
    id: "15",
    name: "Product Team",
    lastMessage: "Next release next week",
    time: "Wed",
    unreadCount: 7,
    avatar: "https://i.pravatar.cc/150?img=15",
    isGroup: true,
    members: ["PM", "Dev", "QA"],
    bio: "Product discussions",
  },
  {
    id: "16",
    name: "Neha Kapoor",
    email: "neha.kapoor@email.com",
    bio: "Writer ✍️",
    lastMessage: "Draft bhej diya",
    time: "Wed",
    unreadCount: 0,
    avatar: "https://i.pravatar.cc/150?img=16",
    isOnline: false,
    lastSeen: "Last seen Wednesday",
    isGroup: false,
  },
  {
    id: "17",
    name: "Travel Friends",
    lastMessage: "Tickets book ho gaye ✈️",
    time: "Tue",
    unreadCount: 2,
    avatar: "https://i.pravatar.cc/150?img=17",
    isGroup: true,
    members: ["Aarav", "Samir", "Pooja"],
    bio: "Trip planning",
  },
  {
    id: "18",
    name: "Karan Arora",
    email: "karan@email.com",
    bio: "Always exploring 🌍",
    lastMessage: "Chalte hain!",
    time: "Tue",
    unreadCount: 0,
    avatar: "https://i.pravatar.cc/150?img=18",
    isOnline: true,
    lastSeen: "Active now",
    isGroup: false,
  },
];
